 -- CREATE VIEW "ELEVI_9A"

 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ELEVI_9A AS
 (
 SELECT NUME_ELEV, PRENUME_ELEV
 FROM COLEGIUL_CODREANU.ELEVI
 WHERE ID_CLASA = '9A'
 )
 WITH CHECK OPTION;
 
 -- CREATE VIEW "ELEVI_9B"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ELEVI_9B AS
 (
 SELECT NUME_ELEV, PRENUME_ELEV
 FROM COLEGIUL_CODREANU.ELEVI
 WHERE ID_CLASA = '9B'
 )
 WITH CHECK OPTION;
 
 -- CREATE VIEW "ELEVI_9C"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ELEVI_9C AS
 (
 SELECT NUME_ELEV, PRENUME_ELEV
 FROM COLEGIUL_CODREANU.ELEVI
 WHERE ID_CLASA = '9C'
 )
 WITH CHECK OPTION;
 
 -- CREATE VIEW "ELEVI_9D"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ELEVI_9D AS
 (
 SELECT NUME_ELEV, PRENUME_ELEV
 FROM COLEGIUL_CODREANU.ELEVI
 WHERE ID_CLASA = '9D'
 )
 WITH CHECK OPTION;
 
 -- CREATE VIEW "ELEVI_9E"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ELEVI_9E AS
 (
 SELECT NUME_ELEV, PRENUME_ELEV
 FROM COLEGIUL_CODREANU.ELEVI
 WHERE ID_CLASA = '9E'
 )
 WITH CHECK OPTION;
 
 -- CREATE VIEW "ELEVI_9F"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ELEVI_9F AS
 (
 SELECT NUME_ELEV, PRENUME_ELEV
 FROM COLEGIUL_CODREANU.ELEVI
 WHERE ID_CLASA = '9F'
 )
 WITH CHECK OPTION;
 
 -- CREATE VIEW "ELEVI_9G"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ELEVI_9G AS
 (
 SELECT NUME_ELEV, PRENUME_ELEV
 FROM COLEGIUL_CODREANU.ELEVI
 WHERE ID_CLASA = '9G'
 )
 WITH CHECK OPTION;
 
 
 
 -- CREATE VIEW "ELEVI_10A"

 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ELEVI_10A AS
 (
 SELECT NUME_ELEV, PRENUME_ELEV
 FROM COLEGIUL_CODREANU.ELEVI
 WHERE ID_CLASA = '10A'
 )
 WITH CHECK OPTION;
 
 -- CREATE VIEW "ELEVI_10B"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ELEVI_10B AS
 (
 SELECT NUME_ELEV, PRENUME_ELEV
 FROM COLEGIUL_CODREANU.ELEVI
 WHERE ID_CLASA = '10B'
 )
 WITH CHECK OPTION;
 
 -- CREATE VIEW "ELEVI_10C"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ELEVI_10C AS
 (
 SELECT NUME_ELEV, PRENUME_ELEV
 FROM COLEGIUL_CODREANU.ELEVI
 WHERE ID_CLASA = '10C'
 )
 WITH CHECK OPTION;
 
 -- CREATE VIEW "ELEVI_10D"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ELEVI_10D AS
 (
 SELECT NUME_ELEV, PRENUME_ELEV
 FROM COLEGIUL_CODREANU.ELEVI
 WHERE ID_CLASA = '10D'
 )
 WITH CHECK OPTION;
 
 -- CREATE VIEW "ELEVI_10E"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ELEVI_10E AS
 (
 SELECT NUME_ELEV, PRENUME_ELEV
 FROM COLEGIUL_CODREANU.ELEVI
 WHERE ID_CLASA = '10E'
 )
 WITH CHECK OPTION;
 
 -- CREATE VIEW "ELEVI_10F"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ELEVI_10F AS
 (
 SELECT NUME_ELEV, PRENUME_ELEV
 FROM COLEGIUL_CODREANU.ELEVI
 WHERE ID_CLASA = '10F'
 )
 WITH CHECK OPTION;
 
 -- CREATE VIEW "ELEVI_10G"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ELEVI_10G AS
 (
 SELECT NUME_ELEV, PRENUME_ELEV
 FROM COLEGIUL_CODREANU.ELEVI
 WHERE ID_CLASA = '10G'
 )
 WITH CHECK OPTION;
 
 
 
 -- CREATE VIEW "ELEVI_11A"

 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ELEVI_11A AS
 (
 SELECT NUME_ELEV, PRENUME_ELEV
 FROM COLEGIUL_CODREANU.ELEVI
 WHERE ID_CLASA = '11A'
 )
 WITH CHECK OPTION;
 
 -- CREATE VIEW "ELEVI_11B"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ELEVI_11B AS
 (
 SELECT NUME_ELEV, PRENUME_ELEV
 FROM COLEGIUL_CODREANU.ELEVI
 WHERE ID_CLASA = '11B'
 )
 WITH CHECK OPTION;
 
 -- CREATE VIEW "ELEVI_11C"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ELEVI_11C AS
 (
 SELECT NUME_ELEV, PRENUME_ELEV
 FROM COLEGIUL_CODREANU.ELEVI
 WHERE ID_CLASA = '11C'
 )
 WITH CHECK OPTION;
 
 -- CREATE VIEW "ELEVI_11D"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ELEVI_11D AS
 (
 SELECT NUME_ELEV, PRENUME_ELEV
 FROM COLEGIUL_CODREANU.ELEVI
 WHERE ID_CLASA = '11D'
 )
 WITH CHECK OPTION;
 
 -- CREATE VIEW "ELEVI_11E"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ELEVI_11E AS
 (
 SELECT NUME_ELEV, PRENUME_ELEV
 FROM COLEGIUL_CODREANU.ELEVI
 WHERE ID_CLASA = '11E'
 )
 WITH CHECK OPTION;
 
 -- CREATE VIEW "ELEVI_11F"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ELEVI_11F AS
 (
 SELECT NUME_ELEV, PRENUME_ELEV
 FROM COLEGIUL_CODREANU.ELEVI
 WHERE ID_CLASA = '11F'
 )
 WITH CHECK OPTION;
 
 -- CREATE VIEW "ELEVI_11G"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ELEVI_11G AS
 (
 SELECT NUME_ELEV, PRENUME_ELEV
 FROM COLEGIUL_CODREANU.ELEVI
 WHERE ID_CLASA = '11G'
 )
 WITH CHECK OPTION;
 
 
 
 -- CREATE VIEW "ELEVI_12A"

 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ELEVI_12A AS
 (
 SELECT NUME_ELEV, PRENUME_ELEV
 FROM COLEGIUL_CODREANU.ELEVI
 WHERE ID_CLASA = '12A'
 )
 WITH CHECK OPTION;
 
 -- CREATE VIEW "ELEVI_12B"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ELEVI_12B AS
 (
 SELECT NUME_ELEV, PRENUME_ELEV
 FROM COLEGIUL_CODREANU.ELEVI
 WHERE ID_CLASA = '12B'
 )
 WITH CHECK OPTION;
 
 -- CREATE VIEW "ELEVI_12C"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ELEVI_12C AS
 (
 SELECT NUME_ELEV, PRENUME_ELEV
 FROM COLEGIUL_CODREANU.ELEVI
 WHERE ID_CLASA = '12C'
 )
 WITH CHECK OPTION;
 
 -- CREATE VIEW "ELEVI_12D"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ELEVI_12D AS
 (
 SELECT NUME_ELEV, PRENUME_ELEV
 FROM COLEGIUL_CODREANU.ELEVI
 WHERE ID_CLASA = '12D'
 )
 WITH CHECK OPTION;
 
 -- CREATE VIEW "ELEVI_12E"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ELEVI_12E AS
 (
 SELECT NUME_ELEV, PRENUME_ELEV
 FROM COLEGIUL_CODREANU.ELEVI
 WHERE ID_CLASA = '12E'
 )
 WITH CHECK OPTION;
 
 -- CREATE VIEW "ELEVI_12F"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ELEVI_12F AS
 (
 SELECT NUME_ELEV, PRENUME_ELEV
 FROM COLEGIUL_CODREANU.ELEVI
 WHERE ID_CLASA = '12F'
 )
 WITH CHECK OPTION;
 
 -- CREATE VIEW "ELEVI_12G"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ELEVI_12G AS
 (
 SELECT NUME_ELEV, PRENUME_ELEV
 FROM COLEGIUL_CODREANU.ELEVI
 WHERE ID_CLASA = '12G'
 )
 WITH CHECK OPTION;
 
  -- CREATE VIEW "PROFESORI_9A"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.PROFESORI_9A AS
 (
 SELECT COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR
 ,      COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR
 ,      COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA
 FROM COLEGIUL_CODREANU.PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE_PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE
 ,    COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI
 WHERE COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_PROFESOR
 AND COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
 AND COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_PROFESORI
 AND COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_CLASA = '9A'
 )
 WITH CHECK OPTION;
 
  -- CREATE VIEW "PROFESORI_9B"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.PROFESORI_9B AS
 (
 SELECT COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR
 ,      COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR
 ,      COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA
 FROM COLEGIUL_CODREANU.PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE_PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE
 ,    COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI
 WHERE COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_PROFESOR
 AND COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
 AND COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_PROFESORI
 AND COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_CLASA = '9B'
 )
 WITH CHECK OPTION;
 
  -- CREATE VIEW "PROFESORI_9C"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.PROFESORI_9C AS
 (
 SELECT COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR
 ,      COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR
 ,      COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA
 FROM COLEGIUL_CODREANU.PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE_PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE
 ,    COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI
 WHERE COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_PROFESOR
 AND COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
 AND COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_PROFESORI
 AND COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_CLASA = '9C'
 )
 WITH CHECK OPTION;
 
  -- CREATE VIEW "PROFESORI_9D"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.PROFESORI_9D AS
 (
 SELECT COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR
 ,      COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR
 ,      COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA
 FROM COLEGIUL_CODREANU.PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE_PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE
 ,    COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI
 WHERE COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_PROFESOR
 AND COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
 AND COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_PROFESORI
 AND COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_CLASA = '9D'
 )
 WITH CHECK OPTION;
 
  -- CREATE VIEW "PROFESORI_9E"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.PROFESORI_9E AS
 (
 SELECT COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR
 ,      COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR
 ,      COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA
 FROM COLEGIUL_CODREANU.PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE_PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE
 ,    COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI
 WHERE COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_PROFESOR
 AND COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
 AND COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_PROFESORI
 AND COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_CLASA = '9E'
 )
 WITH CHECK OPTION;
 
  -- CREATE VIEW "PROFESORI_9F"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.PROFESORI_9F AS
 (
 SELECT COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR
 ,      COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR
 ,      COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA
 FROM COLEGIUL_CODREANU.PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE_PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE
 ,    COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI
 WHERE COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_PROFESOR
 AND COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
 AND COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_PROFESORI
 AND COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_CLASA = '9F'
 )
 WITH CHECK OPTION;
 
  -- CREATE VIEW "PROFESORI_9G"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.PROFESORI_9G AS
 (
 SELECT COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR
 ,      COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR
 ,      COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA
 FROM COLEGIUL_CODREANU.PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE_PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE
 ,    COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI
 WHERE COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_PROFESOR
 AND COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
 AND COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_PROFESORI
 AND COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_CLASA = '9G'
 )
 WITH CHECK OPTION;
 
 
  -- CREATE VIEW "PROFESORI_10A"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.PROFESORI_10A AS
 (
 SELECT COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR
 ,      COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR
 ,      COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA
 FROM COLEGIUL_CODREANU.PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE_PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE
 ,    COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI
 WHERE COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_PROFESOR
 AND COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
 AND COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_PROFESORI
 AND COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_CLASA = '10A'
 )
 WITH CHECK OPTION;
 
  -- CREATE VIEW "PROFESORI_10B"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.PROFESORI_10B AS
 (
 SELECT COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR
 ,      COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR
 ,      COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA
 FROM COLEGIUL_CODREANU.PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE_PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE
 ,    COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI
 WHERE COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_PROFESOR
 AND COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
 AND COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_PROFESORI
 AND COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_CLASA = '10B'
 )
 WITH CHECK OPTION;
 
  -- CREATE VIEW "PROFESORI_10C"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.PROFESORI_10C AS
 (
 SELECT COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR
 ,      COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR
 ,      COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA
 FROM COLEGIUL_CODREANU.PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE_PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE
 ,    COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI
 WHERE COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_PROFESOR
 AND COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
 AND COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_PROFESORI
 AND COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_CLASA = '10C'
 )
 WITH CHECK OPTION;
 
  -- CREATE VIEW "PROFESORI_10D"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.PROFESORI_10D AS
 (
 SELECT COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR
 ,      COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR
 ,      COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA
 FROM COLEGIUL_CODREANU.PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE_PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE
 ,    COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI
 WHERE COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_PROFESOR
 AND COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
 AND COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_PROFESORI
 AND COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_CLASA = '10D'
 )
 WITH CHECK OPTION;
 
  -- CREATE VIEW "PROFESORI_10E"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.PROFESORI_10E AS
 (
 SELECT COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR
 ,      COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR
 ,      COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA
 FROM COLEGIUL_CODREANU.PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE_PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE
 ,    COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI
 WHERE COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_PROFESOR
 AND COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
 AND COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_PROFESORI
 AND COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_CLASA = '10E'
 )
 WITH CHECK OPTION;
 
  -- CREATE VIEW "PROFESORI_10F"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.PROFESORI_10F AS
 (
 SELECT COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR
 ,      COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR
 ,      COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA
 FROM COLEGIUL_CODREANU.PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE_PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE
 ,    COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI
 WHERE COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_PROFESOR
 AND COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
 AND COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_PROFESORI
 AND COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_CLASA = '10F'
 )
 WITH CHECK OPTION;
 
  -- CREATE VIEW "PROFESORI_10G"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.PROFESORI_10G AS
 (
 SELECT COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR
 ,      COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR
 ,      COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA
 FROM COLEGIUL_CODREANU.PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE_PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE
 ,    COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI
 WHERE COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_PROFESOR
 AND COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
 AND COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_PROFESORI
 AND COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_CLASA = '10G'
 )
 WITH CHECK OPTION;
 
  -- CREATE VIEW "PROFESORI_11A"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.PROFESORI_11A AS
 (
 SELECT COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR
 ,      COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR
 ,      COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA
 FROM COLEGIUL_CODREANU.PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE_PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE
 ,    COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI
 WHERE COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_PROFESOR
 AND COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
 AND COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_PROFESORI
 AND COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_CLASA = '11A'
 )
 WITH CHECK OPTION;
 
  -- CREATE VIEW "PROFESORI_11B"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.PROFESORI_11B AS
 (
 SELECT COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR
 ,      COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR
 ,      COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA
 FROM COLEGIUL_CODREANU.PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE_PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE
 ,    COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI
 WHERE COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_PROFESOR
 AND COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
 AND COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_PROFESORI
 AND COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_CLASA = '11B'
 )
 WITH CHECK OPTION;
 
  -- CREATE VIEW "PROFESORI_11C"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.PROFESORI_11C AS
 (
 SELECT COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR
 ,      COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR
 ,      COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA
 FROM COLEGIUL_CODREANU.PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE_PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE
 ,    COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI
 WHERE COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_PROFESOR
 AND COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
 AND COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_PROFESORI
 AND COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_CLASA = '11C'
 )
 WITH CHECK OPTION;
 
  -- CREATE VIEW "PROFESORI_11D"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.PROFESORI_11D AS
 (
 SELECT COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR
 ,      COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR
 ,      COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA
 FROM COLEGIUL_CODREANU.PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE_PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE
 ,    COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI
 WHERE COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_PROFESOR
 AND COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
 AND COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_PROFESORI
 AND COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_CLASA = '11D'
 )
 WITH CHECK OPTION;
 
  -- CREATE VIEW "PROFESORI_11E"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.PROFESORI_11E AS
 (
 SELECT COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR
 ,      COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR
 ,      COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA
 FROM COLEGIUL_CODREANU.PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE_PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE
 ,    COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI
 WHERE COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_PROFESOR
 AND COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
 AND COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_PROFESORI
 AND COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_CLASA = '11E'
 )
 WITH CHECK OPTION;
 
  -- CREATE VIEW "PROFESORI_11F"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.PROFESORI_11F AS
 (
 SELECT COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR
 ,      COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR
 ,      COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA
 FROM COLEGIUL_CODREANU.PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE_PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE
 ,    COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI
 WHERE COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_PROFESOR
 AND COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
 AND COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_PROFESORI
 AND COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_CLASA = '11F'
 )
 WITH CHECK OPTION;
 
  -- CREATE VIEW "PROFESORI_11G"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.PROFESORI_11G AS
 (
 SELECT COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR
 ,      COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR
 ,      COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA
 FROM COLEGIUL_CODREANU.PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE_PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE
 ,    COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI
 WHERE COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_PROFESOR
 AND COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
 AND COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_PROFESORI
 AND COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_CLASA = '11G'
 )
 WITH CHECK OPTION;
 
  -- CREATE VIEW "PROFESORI_12A"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.PROFESORI_12A AS
 (
 SELECT COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR
 ,      COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR
 ,      COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA
 FROM COLEGIUL_CODREANU.PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE_PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE
 ,    COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI
 WHERE COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_PROFESOR
 AND COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
 AND COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_PROFESORI
 AND COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_CLASA = '12A'
 )
 WITH CHECK OPTION;
 
  -- CREATE VIEW "PROFESORI_12B"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.PROFESORI_12B AS
 (
 SELECT COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR
 ,      COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR
 ,      COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA
 FROM COLEGIUL_CODREANU.PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE_PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE
 ,    COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI
 WHERE COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_PROFESOR
 AND COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
 AND COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_PROFESORI
 AND COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_CLASA = '12B'
 )
 WITH CHECK OPTION;
 
  -- CREATE VIEW "PROFESORI_12C"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.PROFESORI_12C AS
 (
 SELECT COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR
 ,      COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR
 ,      COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA
 FROM COLEGIUL_CODREANU.PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE_PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE
 ,    COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI
 WHERE COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_PROFESOR
 AND COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
 AND COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_PROFESORI
 AND COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_CLASA = '12C'
 )
 WITH CHECK OPTION;
 
  -- CREATE VIEW "PROFESORI_12D"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.PROFESORI_12D AS
 (
 SELECT COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR
 ,      COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR
 ,      COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA
 FROM COLEGIUL_CODREANU.PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE_PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE
 ,    COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI
 WHERE COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_PROFESOR
 AND COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
 AND COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_PROFESORI
 AND COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_CLASA = '12D'
 )
 WITH CHECK OPTION;
 
  -- CREATE VIEW "PROFESORI_12E"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.PROFESORI_12E AS
 (
 SELECT COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR
 ,      COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR
 ,      COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA
 FROM COLEGIUL_CODREANU.PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE_PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE
 ,    COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI
 WHERE COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_PROFESOR
 AND COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
 AND COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_PROFESORI
 AND COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_CLASA = '12E'
 )
 WITH CHECK OPTION;
 
  -- CREATE VIEW "PROFESORI_12F"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.PROFESORI_12F AS
 (
 SELECT COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR
 ,      COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR
 ,      COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA
 FROM COLEGIUL_CODREANU.PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE_PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE
 ,    COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI
 WHERE COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_PROFESOR
 AND COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
 AND COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_PROFESORI
 AND COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_CLASA = '12F'
 )
 WITH CHECK OPTION;
 
  -- CREATE VIEW "PROFESORI_12G"
 
 CREATE OR REPLACE VIEW COLEGIUL_CODREANU.PROFESORI_12G AS
 (
 SELECT COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR
 ,      COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR
 ,      COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA
 FROM COLEGIUL_CODREANU.PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE_PROFESORI
 ,    COLEGIUL_CODREANU.DISCIPLINE
 ,    COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI
 WHERE COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_PROFESOR
 AND COLEGIUL_CODREANU.DISCIPLINE_PROFESORI.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
 AND COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR = COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_PROFESORI
 AND COLEGIUL_CODREANU.REPARTITIE_CLASE_PROFESORI.ID_CLASA = '12G'
 )
 WITH CHECK OPTION;

 -- CREATE VIEW ORAR_9A

CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ORAR_9A AS
( 
SELECT COLEGIUL_CODREANU.ORAR.ZI,
	   COLEGIUL_CODREANU.ORAR.ORA,
       COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA AS 'MATERIE',
       CONCAT(COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR, ' ', COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR) AS 'PROFESOR',
       COLEGIUL_CODREANU.SALI.DENUMIRE_SALA AS 'SALA'
FROM COLEGIUL_CODREANU.ORAR,
	 COLEGIUL_CODREANU.DISCIPLINE,
     COLEGIUL_CODREANU.PROFESORI,
     COLEGIUL_CODREANU.SALI
WHERE COLEGIUL_CODREANU.ORAR.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
AND COLEGIUL_CODREANU.ORAR.ID_PROFESOR = COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR
AND COLEGIUL_CODREANU.ORAR.ID_SALA = COLEGIUL_CODREANU.SALI.ID_SALA
AND ID_CLASA = '9A'
ORDER BY ZI, ORA
)
WITH CHECK OPTION;

 -- CREATE VIEW ORAR_9B

CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ORAR_9B AS
( 
SELECT COLEGIUL_CODREANU.ORAR.ZI,
	   COLEGIUL_CODREANU.ORAR.ORA,
       COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA AS 'MATERIE',
       CONCAT(COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR, ' ', COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR) AS 'PROFESOR',
       COLEGIUL_CODREANU.SALI.DENUMIRE_SALA AS 'SALA'
FROM COLEGIUL_CODREANU.ORAR,
	 COLEGIUL_CODREANU.DISCIPLINE,
     COLEGIUL_CODREANU.PROFESORI,
     COLEGIUL_CODREANU.SALI
WHERE COLEGIUL_CODREANU.ORAR.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
AND COLEGIUL_CODREANU.ORAR.ID_PROFESOR = COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR
AND COLEGIUL_CODREANU.ORAR.ID_SALA = COLEGIUL_CODREANU.SALI.ID_SALA
AND ID_CLASA = '9B'
ORDER BY ZI, ORA
)
WITH CHECK OPTION;

 -- CREATE VIEW ORAR_9C

CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ORAR_9C AS
( 
SELECT COLEGIUL_CODREANU.ORAR.ZI,
	   COLEGIUL_CODREANU.ORAR.ORA,
       COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA AS 'MATERIE',
       CONCAT(COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR, ' ', COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR) AS 'PROFESOR',
       COLEGIUL_CODREANU.SALI.DENUMIRE_SALA AS 'SALA'
FROM COLEGIUL_CODREANU.ORAR,
	 COLEGIUL_CODREANU.DISCIPLINE,
     COLEGIUL_CODREANU.PROFESORI,
     COLEGIUL_CODREANU.SALI
WHERE COLEGIUL_CODREANU.ORAR.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
AND COLEGIUL_CODREANU.ORAR.ID_PROFESOR = COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR
AND COLEGIUL_CODREANU.ORAR.ID_SALA = COLEGIUL_CODREANU.SALI.ID_SALA
AND ID_CLASA = '9C'
ORDER BY ZI, ORA
)
WITH CHECK OPTION;

 -- CREATE VIEW ORAR_9D

CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ORAR_9D AS
( 
SELECT COLEGIUL_CODREANU.ORAR.ZI,
	   COLEGIUL_CODREANU.ORAR.ORA,
       COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA AS 'MATERIE',
       CONCAT(COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR, ' ', COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR) AS 'PROFESOR',
       COLEGIUL_CODREANU.SALI.DENUMIRE_SALA AS 'SALA'
FROM COLEGIUL_CODREANU.ORAR,
	 COLEGIUL_CODREANU.DISCIPLINE,
     COLEGIUL_CODREANU.PROFESORI,
     COLEGIUL_CODREANU.SALI
WHERE COLEGIUL_CODREANU.ORAR.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
AND COLEGIUL_CODREANU.ORAR.ID_PROFESOR = COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR
AND COLEGIUL_CODREANU.ORAR.ID_SALA = COLEGIUL_CODREANU.SALI.ID_SALA
AND ID_CLASA = '9D'
ORDER BY ZI, ORA
)
WITH CHECK OPTION;

 -- CREATE VIEW ORAR_9E

CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ORAR_9E AS
( 
SELECT COLEGIUL_CODREANU.ORAR.ZI,
	   COLEGIUL_CODREANU.ORAR.ORA,
       COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA AS 'MATERIE',
       CONCAT(COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR, ' ', COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR) AS 'PROFESOR',
       COLEGIUL_CODREANU.SALI.DENUMIRE_SALA AS 'SALA'
FROM COLEGIUL_CODREANU.ORAR,
	 COLEGIUL_CODREANU.DISCIPLINE,
     COLEGIUL_CODREANU.PROFESORI,
     COLEGIUL_CODREANU.SALI
WHERE COLEGIUL_CODREANU.ORAR.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
AND COLEGIUL_CODREANU.ORAR.ID_PROFESOR = COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR
AND COLEGIUL_CODREANU.ORAR.ID_SALA = COLEGIUL_CODREANU.SALI.ID_SALA
AND ID_CLASA = '9E'
ORDER BY ZI, ORA
)
WITH CHECK OPTION;

 -- CREATE VIEW ORAR_9F

CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ORAR_9F AS
( 
SELECT COLEGIUL_CODREANU.ORAR.ZI,
	   COLEGIUL_CODREANU.ORAR.ORA,
       COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA AS 'MATERIE',
       CONCAT(COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR, ' ', COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR) AS 'PROFESOR',
       COLEGIUL_CODREANU.SALI.DENUMIRE_SALA AS 'SALA'
FROM COLEGIUL_CODREANU.ORAR,
	 COLEGIUL_CODREANU.DISCIPLINE,
     COLEGIUL_CODREANU.PROFESORI,
     COLEGIUL_CODREANU.SALI
WHERE COLEGIUL_CODREANU.ORAR.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
AND COLEGIUL_CODREANU.ORAR.ID_PROFESOR = COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR
AND COLEGIUL_CODREANU.ORAR.ID_SALA = COLEGIUL_CODREANU.SALI.ID_SALA
AND ID_CLASA = '9F'
ORDER BY ZI, ORA
)
WITH CHECK OPTION;

 -- CREATE VIEW ORAR_9G

CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ORAR_9G AS
( 
SELECT COLEGIUL_CODREANU.ORAR.ZI,
	   COLEGIUL_CODREANU.ORAR.ORA,
       COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA AS 'MATERIE',
       CONCAT(COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR, ' ', COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR) AS 'PROFESOR',
       COLEGIUL_CODREANU.SALI.DENUMIRE_SALA AS 'SALA'
FROM COLEGIUL_CODREANU.ORAR,
	 COLEGIUL_CODREANU.DISCIPLINE,
     COLEGIUL_CODREANU.PROFESORI,
     COLEGIUL_CODREANU.SALI
WHERE COLEGIUL_CODREANU.ORAR.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
AND COLEGIUL_CODREANU.ORAR.ID_PROFESOR = COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR
AND COLEGIUL_CODREANU.ORAR.ID_SALA = COLEGIUL_CODREANU.SALI.ID_SALA
AND ID_CLASA = '9G'
ORDER BY ZI, ORA
)
WITH CHECK OPTION;

 -- CREATE VIEW ORAR_10A

CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ORAR_10A AS
( 
SELECT COLEGIUL_CODREANU.ORAR.ZI,
	   COLEGIUL_CODREANU.ORAR.ORA,
       COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA AS 'MATERIE',
       CONCAT(COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR, ' ', COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR) AS 'PROFESOR',
       COLEGIUL_CODREANU.SALI.DENUMIRE_SALA AS 'SALA'
FROM COLEGIUL_CODREANU.ORAR,
	 COLEGIUL_CODREANU.DISCIPLINE,
     COLEGIUL_CODREANU.PROFESORI,
     COLEGIUL_CODREANU.SALI
WHERE COLEGIUL_CODREANU.ORAR.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
AND COLEGIUL_CODREANU.ORAR.ID_PROFESOR = COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR
AND COLEGIUL_CODREANU.ORAR.ID_SALA = COLEGIUL_CODREANU.SALI.ID_SALA
AND ID_CLASA = '10A'
ORDER BY ZI, ORA
)
WITH CHECK OPTION;

 -- CREATE VIEW ORAR_10B

CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ORAR_10B AS
( 
SELECT COLEGIUL_CODREANU.ORAR.ZI,
	   COLEGIUL_CODREANU.ORAR.ORA,
       COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA AS 'MATERIE',
       CONCAT(COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR, ' ', COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR) AS 'PROFESOR',
       COLEGIUL_CODREANU.SALI.DENUMIRE_SALA AS 'SALA'
FROM COLEGIUL_CODREANU.ORAR,
	 COLEGIUL_CODREANU.DISCIPLINE,
     COLEGIUL_CODREANU.PROFESORI,
     COLEGIUL_CODREANU.SALI
WHERE COLEGIUL_CODREANU.ORAR.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
AND COLEGIUL_CODREANU.ORAR.ID_PROFESOR = COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR
AND COLEGIUL_CODREANU.ORAR.ID_SALA = COLEGIUL_CODREANU.SALI.ID_SALA
AND ID_CLASA = '10B'
ORDER BY ZI, ORA
)
WITH CHECK OPTION;

 -- CREATE VIEW ORAR_10C

CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ORAR_10C AS
( 
SELECT COLEGIUL_CODREANU.ORAR.ZI,
	   COLEGIUL_CODREANU.ORAR.ORA,
       COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA AS 'MATERIE',
       CONCAT(COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR, ' ', COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR) AS 'PROFESOR',
       COLEGIUL_CODREANU.SALI.DENUMIRE_SALA AS 'SALA'
FROM COLEGIUL_CODREANU.ORAR,
	 COLEGIUL_CODREANU.DISCIPLINE,
     COLEGIUL_CODREANU.PROFESORI,
     COLEGIUL_CODREANU.SALI
WHERE COLEGIUL_CODREANU.ORAR.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
AND COLEGIUL_CODREANU.ORAR.ID_PROFESOR = COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR
AND COLEGIUL_CODREANU.ORAR.ID_SALA = COLEGIUL_CODREANU.SALI.ID_SALA
AND ID_CLASA = '10C'
ORDER BY ZI, ORA
)
WITH CHECK OPTION;

 -- CREATE VIEW ORAR_10D

CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ORAR_10D AS
( 
SELECT COLEGIUL_CODREANU.ORAR.ZI,
	   COLEGIUL_CODREANU.ORAR.ORA,
       COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA AS 'MATERIE',
       CONCAT(COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR, ' ', COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR) AS 'PROFESOR',
       COLEGIUL_CODREANU.SALI.DENUMIRE_SALA AS 'SALA'
FROM COLEGIUL_CODREANU.ORAR,
	 COLEGIUL_CODREANU.DISCIPLINE,
     COLEGIUL_CODREANU.PROFESORI,
     COLEGIUL_CODREANU.SALI
WHERE COLEGIUL_CODREANU.ORAR.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
AND COLEGIUL_CODREANU.ORAR.ID_PROFESOR = COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR
AND COLEGIUL_CODREANU.ORAR.ID_SALA = COLEGIUL_CODREANU.SALI.ID_SALA
AND ID_CLASA = '10D'
ORDER BY ZI, ORA
)
WITH CHECK OPTION;

 -- CREATE VIEW ORAR_10E

CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ORAR_10E AS
( 
SELECT COLEGIUL_CODREANU.ORAR.ZI,
	   COLEGIUL_CODREANU.ORAR.ORA,
       COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA AS 'MATERIE',
       CONCAT(COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR, ' ', COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR) AS 'PROFESOR',
       COLEGIUL_CODREANU.SALI.DENUMIRE_SALA AS 'SALA'
FROM COLEGIUL_CODREANU.ORAR,
	 COLEGIUL_CODREANU.DISCIPLINE,
     COLEGIUL_CODREANU.PROFESORI,
     COLEGIUL_CODREANU.SALI
WHERE COLEGIUL_CODREANU.ORAR.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
AND COLEGIUL_CODREANU.ORAR.ID_PROFESOR = COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR
AND COLEGIUL_CODREANU.ORAR.ID_SALA = COLEGIUL_CODREANU.SALI.ID_SALA
AND ID_CLASA = '10E'
ORDER BY ZI, ORA
)
WITH CHECK OPTION;

 -- CREATE VIEW ORAR_10F

CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ORAR_10F AS
( 
SELECT COLEGIUL_CODREANU.ORAR.ZI,
	   COLEGIUL_CODREANU.ORAR.ORA,
       COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA AS 'MATERIE',
       CONCAT(COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR, ' ', COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR) AS 'PROFESOR',
       COLEGIUL_CODREANU.SALI.DENUMIRE_SALA AS 'SALA'
FROM COLEGIUL_CODREANU.ORAR,
	 COLEGIUL_CODREANU.DISCIPLINE,
     COLEGIUL_CODREANU.PROFESORI,
     COLEGIUL_CODREANU.SALI
WHERE COLEGIUL_CODREANU.ORAR.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
AND COLEGIUL_CODREANU.ORAR.ID_PROFESOR = COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR
AND COLEGIUL_CODREANU.ORAR.ID_SALA = COLEGIUL_CODREANU.SALI.ID_SALA
AND ID_CLASA = '10F'
ORDER BY ZI, ORA
)
WITH CHECK OPTION;

 -- CREATE VIEW ORAR_10G

CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ORAR_10G AS
( 
SELECT COLEGIUL_CODREANU.ORAR.ZI,
	   COLEGIUL_CODREANU.ORAR.ORA,
       COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA AS 'MATERIE',
       CONCAT(COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR, ' ', COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR) AS 'PROFESOR',
       COLEGIUL_CODREANU.SALI.DENUMIRE_SALA AS 'SALA'
FROM COLEGIUL_CODREANU.ORAR,
	 COLEGIUL_CODREANU.DISCIPLINE,
     COLEGIUL_CODREANU.PROFESORI,
     COLEGIUL_CODREANU.SALI
WHERE COLEGIUL_CODREANU.ORAR.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
AND COLEGIUL_CODREANU.ORAR.ID_PROFESOR = COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR
AND COLEGIUL_CODREANU.ORAR.ID_SALA = COLEGIUL_CODREANU.SALI.ID_SALA
AND ID_CLASA = '10G'
ORDER BY ZI, ORA
)
WITH CHECK OPTION;

 -- CREATE VIEW ORAR_11A

CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ORAR_11A AS
( 
SELECT COLEGIUL_CODREANU.ORAR.ZI,
	   COLEGIUL_CODREANU.ORAR.ORA,
       COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA AS 'MATERIE',
       CONCAT(COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR, ' ', COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR) AS 'PROFESOR',
       COLEGIUL_CODREANU.SALI.DENUMIRE_SALA AS 'SALA'
FROM COLEGIUL_CODREANU.ORAR,
	 COLEGIUL_CODREANU.DISCIPLINE,
     COLEGIUL_CODREANU.PROFESORI,
     COLEGIUL_CODREANU.SALI
WHERE COLEGIUL_CODREANU.ORAR.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
AND COLEGIUL_CODREANU.ORAR.ID_PROFESOR = COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR
AND COLEGIUL_CODREANU.ORAR.ID_SALA = COLEGIUL_CODREANU.SALI.ID_SALA
AND ID_CLASA = '11A'
ORDER BY ZI, ORA
)
WITH CHECK OPTION;

 -- CREATE VIEW ORAR_11B

CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ORAR_11B AS
( 
SELECT COLEGIUL_CODREANU.ORAR.ZI,
	   COLEGIUL_CODREANU.ORAR.ORA,
       COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA AS 'MATERIE',
       CONCAT(COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR, ' ', COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR) AS 'PROFESOR',
       COLEGIUL_CODREANU.SALI.DENUMIRE_SALA AS 'SALA'
FROM COLEGIUL_CODREANU.ORAR,
	 COLEGIUL_CODREANU.DISCIPLINE,
     COLEGIUL_CODREANU.PROFESORI,
     COLEGIUL_CODREANU.SALI
WHERE COLEGIUL_CODREANU.ORAR.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
AND COLEGIUL_CODREANU.ORAR.ID_PROFESOR = COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR
AND COLEGIUL_CODREANU.ORAR.ID_SALA = COLEGIUL_CODREANU.SALI.ID_SALA
AND ID_CLASA = '11B'
ORDER BY ZI, ORA
)
WITH CHECK OPTION;

 -- CREATE VIEW ORAR_11C

CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ORAR_11C AS
( 
SELECT COLEGIUL_CODREANU.ORAR.ZI,
	   COLEGIUL_CODREANU.ORAR.ORA,
       COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA AS 'MATERIE',
       CONCAT(COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR, ' ', COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR) AS 'PROFESOR',
       COLEGIUL_CODREANU.SALI.DENUMIRE_SALA AS 'SALA'
FROM COLEGIUL_CODREANU.ORAR,
	 COLEGIUL_CODREANU.DISCIPLINE,
     COLEGIUL_CODREANU.PROFESORI,
     COLEGIUL_CODREANU.SALI
WHERE COLEGIUL_CODREANU.ORAR.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
AND COLEGIUL_CODREANU.ORAR.ID_PROFESOR = COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR
AND COLEGIUL_CODREANU.ORAR.ID_SALA = COLEGIUL_CODREANU.SALI.ID_SALA
AND ID_CLASA = '11C'
ORDER BY ZI, ORA
)
WITH CHECK OPTION;

 -- CREATE VIEW ORAR_11D

CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ORAR_11D AS
( 
SELECT COLEGIUL_CODREANU.ORAR.ZI,
	   COLEGIUL_CODREANU.ORAR.ORA,
       COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA AS 'MATERIE',
       CONCAT(COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR, ' ', COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR) AS 'PROFESOR',
       COLEGIUL_CODREANU.SALI.DENUMIRE_SALA AS 'SALA'
FROM COLEGIUL_CODREANU.ORAR,
	 COLEGIUL_CODREANU.DISCIPLINE,
     COLEGIUL_CODREANU.PROFESORI,
     COLEGIUL_CODREANU.SALI
WHERE COLEGIUL_CODREANU.ORAR.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
AND COLEGIUL_CODREANU.ORAR.ID_PROFESOR = COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR
AND COLEGIUL_CODREANU.ORAR.ID_SALA = COLEGIUL_CODREANU.SALI.ID_SALA
AND ID_CLASA = '11D'
ORDER BY ZI, ORA
)
WITH CHECK OPTION;

 -- CREATE VIEW ORAR_11E

CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ORAR_11E AS
( 
SELECT COLEGIUL_CODREANU.ORAR.ZI,
	   COLEGIUL_CODREANU.ORAR.ORA,
       COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA AS 'MATERIE',
       CONCAT(COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR, ' ', COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR) AS 'PROFESOR',
       COLEGIUL_CODREANU.SALI.DENUMIRE_SALA AS 'SALA'
FROM COLEGIUL_CODREANU.ORAR,
	 COLEGIUL_CODREANU.DISCIPLINE,
     COLEGIUL_CODREANU.PROFESORI,
     COLEGIUL_CODREANU.SALI
WHERE COLEGIUL_CODREANU.ORAR.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
AND COLEGIUL_CODREANU.ORAR.ID_PROFESOR = COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR
AND COLEGIUL_CODREANU.ORAR.ID_SALA = COLEGIUL_CODREANU.SALI.ID_SALA
AND ID_CLASA = '11E'
ORDER BY ZI, ORA
)
WITH CHECK OPTION;

 -- CREATE VIEW ORAR_11F

CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ORAR_11F AS
( 
SELECT COLEGIUL_CODREANU.ORAR.ZI,
	   COLEGIUL_CODREANU.ORAR.ORA,
       COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA AS 'MATERIE',
       CONCAT(COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR, ' ', COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR) AS 'PROFESOR',
       COLEGIUL_CODREANU.SALI.DENUMIRE_SALA AS 'SALA'
FROM COLEGIUL_CODREANU.ORAR,
	 COLEGIUL_CODREANU.DISCIPLINE,
     COLEGIUL_CODREANU.PROFESORI,
     COLEGIUL_CODREANU.SALI
WHERE COLEGIUL_CODREANU.ORAR.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
AND COLEGIUL_CODREANU.ORAR.ID_PROFESOR = COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR
AND COLEGIUL_CODREANU.ORAR.ID_SALA = COLEGIUL_CODREANU.SALI.ID_SALA
AND ID_CLASA = '11F'
ORDER BY ZI, ORA
)
WITH CHECK OPTION;

 -- CREATE VIEW ORAR_11G

CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ORAR_11G AS
( 
SELECT COLEGIUL_CODREANU.ORAR.ZI,
	   COLEGIUL_CODREANU.ORAR.ORA,
       COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA AS 'MATERIE',
       CONCAT(COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR, ' ', COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR) AS 'PROFESOR',
       COLEGIUL_CODREANU.SALI.DENUMIRE_SALA AS 'SALA'
FROM COLEGIUL_CODREANU.ORAR,
	 COLEGIUL_CODREANU.DISCIPLINE,
     COLEGIUL_CODREANU.PROFESORI,
     COLEGIUL_CODREANU.SALI
WHERE COLEGIUL_CODREANU.ORAR.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
AND COLEGIUL_CODREANU.ORAR.ID_PROFESOR = COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR
AND COLEGIUL_CODREANU.ORAR.ID_SALA = COLEGIUL_CODREANU.SALI.ID_SALA
AND ID_CLASA = '11G'
ORDER BY ZI, ORA
)
WITH CHECK OPTION;

 -- CREATE VIEW ORAR_12A

CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ORAR_12A AS
( 
SELECT COLEGIUL_CODREANU.ORAR.ZI,
	   COLEGIUL_CODREANU.ORAR.ORA,
       COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA AS 'MATERIE',
       CONCAT(COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR, ' ', COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR) AS 'PROFESOR',
       COLEGIUL_CODREANU.SALI.DENUMIRE_SALA AS 'SALA'
FROM COLEGIUL_CODREANU.ORAR,
	 COLEGIUL_CODREANU.DISCIPLINE,
     COLEGIUL_CODREANU.PROFESORI,
     COLEGIUL_CODREANU.SALI
WHERE COLEGIUL_CODREANU.ORAR.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
AND COLEGIUL_CODREANU.ORAR.ID_PROFESOR = COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR
AND COLEGIUL_CODREANU.ORAR.ID_SALA = COLEGIUL_CODREANU.SALI.ID_SALA
AND ID_CLASA = '12A'
ORDER BY ZI, ORA
)
WITH CHECK OPTION;

 -- CREATE VIEW ORAR_12B

CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ORAR_12B AS
( 
SELECT COLEGIUL_CODREANU.ORAR.ZI,
	   COLEGIUL_CODREANU.ORAR.ORA,
       COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA AS 'MATERIE',
       CONCAT(COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR, ' ', COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR) AS 'PROFESOR',
       COLEGIUL_CODREANU.SALI.DENUMIRE_SALA AS 'SALA'
FROM COLEGIUL_CODREANU.ORAR,
	 COLEGIUL_CODREANU.DISCIPLINE,
     COLEGIUL_CODREANU.PROFESORI,
     COLEGIUL_CODREANU.SALI
WHERE COLEGIUL_CODREANU.ORAR.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
AND COLEGIUL_CODREANU.ORAR.ID_PROFESOR = COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR
AND COLEGIUL_CODREANU.ORAR.ID_SALA = COLEGIUL_CODREANU.SALI.ID_SALA
AND ID_CLASA = '12B'
ORDER BY ZI, ORA
)
WITH CHECK OPTION;

 -- CREATE VIEW ORAR_12C

CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ORAR_12C AS
( 
SELECT COLEGIUL_CODREANU.ORAR.ZI,
	   COLEGIUL_CODREANU.ORAR.ORA,
       COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA AS 'MATERIE',
       CONCAT(COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR, ' ', COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR) AS 'PROFESOR',
       COLEGIUL_CODREANU.SALI.DENUMIRE_SALA AS 'SALA'
FROM COLEGIUL_CODREANU.ORAR,
	 COLEGIUL_CODREANU.DISCIPLINE,
     COLEGIUL_CODREANU.PROFESORI,
     COLEGIUL_CODREANU.SALI
WHERE COLEGIUL_CODREANU.ORAR.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
AND COLEGIUL_CODREANU.ORAR.ID_PROFESOR = COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR
AND COLEGIUL_CODREANU.ORAR.ID_SALA = COLEGIUL_CODREANU.SALI.ID_SALA
AND ID_CLASA = '12C'
ORDER BY ZI, ORA
)
WITH CHECK OPTION;

 -- CREATE VIEW ORAR_12D

CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ORAR_12D AS
( 
SELECT COLEGIUL_CODREANU.ORAR.ZI,
	   COLEGIUL_CODREANU.ORAR.ORA,
       COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA AS 'MATERIE',
       CONCAT(COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR, ' ', COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR) AS 'PROFESOR',
       COLEGIUL_CODREANU.SALI.DENUMIRE_SALA AS 'SALA'
FROM COLEGIUL_CODREANU.ORAR,
	 COLEGIUL_CODREANU.DISCIPLINE,
     COLEGIUL_CODREANU.PROFESORI,
     COLEGIUL_CODREANU.SALI
WHERE COLEGIUL_CODREANU.ORAR.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
AND COLEGIUL_CODREANU.ORAR.ID_PROFESOR = COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR
AND COLEGIUL_CODREANU.ORAR.ID_SALA = COLEGIUL_CODREANU.SALI.ID_SALA
AND ID_CLASA = '12D'
ORDER BY ZI, ORA
)
WITH CHECK OPTION;

 -- CREATE VIEW ORAR_12E

CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ORAR_12E AS
( 
SELECT COLEGIUL_CODREANU.ORAR.ZI,
	   COLEGIUL_CODREANU.ORAR.ORA,
       COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA AS 'MATERIE',
       CONCAT(COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR, ' ', COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR) AS 'PROFESOR',
       COLEGIUL_CODREANU.SALI.DENUMIRE_SALA AS 'SALA'
FROM COLEGIUL_CODREANU.ORAR,
	 COLEGIUL_CODREANU.DISCIPLINE,
     COLEGIUL_CODREANU.PROFESORI,
     COLEGIUL_CODREANU.SALI
WHERE COLEGIUL_CODREANU.ORAR.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
AND COLEGIUL_CODREANU.ORAR.ID_PROFESOR = COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR
AND COLEGIUL_CODREANU.ORAR.ID_SALA = COLEGIUL_CODREANU.SALI.ID_SALA
AND ID_CLASA = '12E'
ORDER BY ZI, ORA
)
WITH CHECK OPTION;

 -- CREATE VIEW ORAR_12F

CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ORAR_12F AS
( 
SELECT COLEGIUL_CODREANU.ORAR.ZI,
	   COLEGIUL_CODREANU.ORAR.ORA,
       COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA AS 'MATERIE',
       CONCAT(COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR, ' ', COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR) AS 'PROFESOR',
       COLEGIUL_CODREANU.SALI.DENUMIRE_SALA AS 'SALA'
FROM COLEGIUL_CODREANU.ORAR,
	 COLEGIUL_CODREANU.DISCIPLINE,
     COLEGIUL_CODREANU.PROFESORI,
     COLEGIUL_CODREANU.SALI
WHERE COLEGIUL_CODREANU.ORAR.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
AND COLEGIUL_CODREANU.ORAR.ID_PROFESOR = COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR
AND COLEGIUL_CODREANU.ORAR.ID_SALA = COLEGIUL_CODREANU.SALI.ID_SALA
AND ID_CLASA = '12F'
ORDER BY ZI, ORA
)
WITH CHECK OPTION;

 -- CREATE VIEW ORAR_12G

CREATE OR REPLACE VIEW COLEGIUL_CODREANU.ORAR_12G AS
( 
SELECT COLEGIUL_CODREANU.ORAR.ZI,
	   COLEGIUL_CODREANU.ORAR.ORA,
       COLEGIUL_CODREANU.DISCIPLINE.DENUMIRE_DISCIPLINA AS 'MATERIE',
       CONCAT(COLEGIUL_CODREANU.PROFESORI.PRENUME_PROFESOR, ' ', COLEGIUL_CODREANU.PROFESORI.NUME_PROFESOR) AS 'PROFESOR',
       COLEGIUL_CODREANU.SALI.DENUMIRE_SALA AS 'SALA'
FROM COLEGIUL_CODREANU.ORAR,
	 COLEGIUL_CODREANU.DISCIPLINE,
     COLEGIUL_CODREANU.PROFESORI,
     COLEGIUL_CODREANU.SALI
WHERE COLEGIUL_CODREANU.ORAR.ID_DISCIPLINA = COLEGIUL_CODREANU.DISCIPLINE.ID_DISCIPLINA
AND COLEGIUL_CODREANU.ORAR.ID_PROFESOR = COLEGIUL_CODREANU.PROFESORI.ID_PROFESOR
AND COLEGIUL_CODREANU.ORAR.ID_SALA = COLEGIUL_CODREANU.SALI.ID_SALA
AND ID_CLASA = '12G'
ORDER BY ZI, ORA
)
WITH CHECK OPTION;

